# Generated by Django 3.2 on 2021-06-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webster', '0007_auto_20210616_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(default='', upload_to='filess'),
        ),
    ]
